# Generated by Django 5.2.4 on 2025-07-25 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='انجام شده'),
        ),
    ]
